### ISSUE TITLE
Error with setup.py when using SSH keys

### ISSUE THREAD

**Issue by williamcaput** [trustedsec/tap#3]
Setup script finishes with password authentication. When choosing Private/Public Key, it crashes after prompting for password.

Enter your password for the remote SSH server:
Traceback (most recent call last):
  File "setup.py", line 262, in <module>
    child.expect("password")
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 102, in expect_loop
    return self.eof(e)
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 49, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f91b411e3d0>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'somename@x.x.x.x', '-p', '22']
searcher: None
buffer (last 100 chars): ''
before (last 100 chars): "nently added 'x.x.x.x' (ECDSA) to the list of known hosts.\r\r\nPermission denied (publickey).\r\r\n"
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 255
flag_eof: True
pid: 29743
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
root@xxx-TAP:/home/xxx/tap#

**Comment by HackingDave** [comment]
Fixed, thanks!
